name: Rust Build and Test (Arm64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: | # TODO: Cache cargo files (See: https://github.com/crow-rest/cargo-prebuilt-index/blob/main/.github/workflows/cargo-audit.yml)
            target
          key: ${{ runner.os }}-aarch64-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker CMD
        run: |
          docker run --rm \
          --platform linux/arm64 \
          -v ${{ github.workspace }}:/build -w /build \
          rust:latest \
          bash -c 'rustc --version && cargo test --verbose --workspace --all-features && cargo build --verbose --workspace'
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-linux-aarch64
          path: |
            target/debug/allot

  build-macos-aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-aarch64-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update Rust
        run: rustup update
      - name: Rust Version
        run: rustc --version
      - name: Add Rust target
        run: rustup target add aarch64-apple-darwin
      - name: MacOS SDK
        run: |
          export SDKROOT=$(xcrun -sdk macosx --show-sdk-path)
          export MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)
      # Cannot test aarch64 MacOS binaries
      - name: Build
        run: cargo build --verbose --workspace --target=aarch64-apple-darwin
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-macos-aarch64
          path: |
            target/aarch64-apple-darwin/debug/allot

# No windows aarch64
